### model
model_name_or_path: YOUR_DIR/models/gemma-2b


### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: bioinstruct
template: gemma
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16
dataset_dir: YOUR_DIR/STAFF/finetune/data
tokenized_path: YOUR_DIR/STAFF/finetune/data/bioinstruct_dataset-gemma-2b


### output
output_dir: YOUR_DIR/bioinstruct_gemma2-factory-sft
logging_steps: 10
save_steps: 1000
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000


### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: epoch

